// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Success response payload for getting a random joke
 */
export const GetRandomJokeSuccessResponsePayloadSchema = z
  .object({
    id: z.string().register(z.globalRegistry, {
      description: "Unique identifier of the joke",
    }),
    joke: z.string().register(z.globalRegistry, {
      description: "The text of the joke",
    }),
    status: z.literal(200).register(z.globalRegistry, {
      description: "Status code of the response",
    }),
  })
  .register(z.globalRegistry, {
    description: "Success response payload for getting a random joke",
  });

export const GetRandomJokeRequestSchema = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful response with a random joke
 */
export const GetRandomJokeResponseSchema =
  GetRandomJokeSuccessResponsePayloadSchema;
